name: loggregator

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: loggregator
  version: latest
- name: etcd
  version: latest
- name: consul
  version: latest

instance_groups:
- name: testing-blobs
  azs:
  - z1
  instances: 1
  persistent_disk_type: 1GB
  vm_type: common
  stemcell: default
  networks:
  - name: loggregator
  jobs:
  - name: boshhmforwarder
    release: loggregator
  - name: dea_logging_agent
    release: loggregator
- name: consul
  azs:
  - z1
  instances: 1
  persistent_disk_type: 1GB
  vm_type: common
  stemcell: default
  networks:
  - name: loggregator
    static_ips: [10.244.10.2]
  jobs:
  - name: consul_agent
    release: consul
    properties:
      consul:
        agent:
          mode: server
          domain: cf.internal
          servers: &consul_servers
            lan: [10.244.10.2]
        require_ssl: true
        encrypt_keys: "((consul_encrypt_keys))"
        agent_cert: "((consul_agent.certificate))"
        agent_key: "((consul_agent.private_key))"
        ca_cert: "((consul_server.ca))"
        server_cert: "((consul_server.certificate))"
        server_key: "((consul_server.private_key))"
  - name: metron_agent
    release: loggregator
    properties: &metron_agent_properties
      doppler:
        addr: doppler.service.cf.internal
      metron_agent:
        protocols:
        - udp
        deployment: loggregator
        etcd:
          client_cert: "((etcd_client.certificate))"
          client_key: "((etcd_client.private_key))"
      metron_endpoint:
        shared_secret: "((dropsonde_shared_secret))"
      loggregator:
        tls:
          ca_cert: "((loggregator_tls_ca_cert))"
          metron:
            cert: "((metron_agent_tls_client_cert))"
            key: "((metron_agent_tls_client_key))"
        etcd:
          require_ssl: true
          ca_cert: "((etcd_client.ca))"
          machines: [etcd.service.cf.internal]
  update:
    serial: true
    max_in_flight: 1

- name: loggregator-acceptance-tests
  azs:
  - z1
  instances: 1
  vm_type: common
  stemcell: default
  lifecycle: errand
  networks:
  - name: loggregator
  jobs:
  - name: loggregator-acceptance-tests
    release: loggregator
    properties:
      traffic_controller:
        disable_access_control: true
      loggregator:
        etcd:
          require_ssl: true
          ca_cert: "((etcd_client.ca))"
          machines: [etcd.service.cf.internal]
      loggregator_acceptance_tests:
        etcd:
          cert: "((etcd_client.certificate))"
          key: "((etcd_client.private_key))"
      loggregator_endpoint:
        shared_secret: "((dropsonde_shared_secret))"
      etcd:
        machines: [etcd.service.cf.internal]
  - name: consul_agent
    release: consul
    properties:
      consul:
        agent:
          mode: client
          domain: cf.internal
          servers: *consul_servers
          services:
            etcd:
              name: etcd
        require_ssl: true
        encrypt_keys: "((consul_encrypt_keys))"
        agent_cert: "((consul_agent.certificate))"
        agent_key: "((consul_agent.private_key))"
        ca_cert: "((consul_agent.ca))"
        server_cert: "((consul_server.certificate))"
        server_key: "((consul_server.private_key))"
  - name: metron_agent
    release: loggregator
    properties: *metron_agent_properties


- name: etcd
  azs:
  - z1
  instances: 1
  persistent_disk_type: 1GB
  vm_type: common
  stemcell: default
  networks:
  - name: loggregator
  jobs:
  - name: consul_agent
    release: consul
    properties:
      consul:
        agent:
          mode: client
          domain: cf.internal
          servers: *consul_servers
          services:
            etcd:
              name: etcd
        require_ssl: true
        encrypt_keys: "((consul_encrypt_keys))"
        agent_cert: "((consul_agent.certificate))"
        agent_key: "((consul_agent.private_key))"
        ca_cert: "((consul_agent.ca))"
        server_cert: "((consul_server.certificate))"
        server_key: "((consul_server.private_key))"
  - name: etcd
    release: etcd
    properties:
      etcd:
        advertise_urls_dns_suffix: etcd.service.cf.internal
        cluster:
        - instances: 1
          name: etcd
        machines: [etcd.service.cf.internal]
        peer_require_ssl: true
        require_ssl: true
        ca_cert: "((etcd_server.ca))"
        client_cert: "((etcd_client.certificate))"
        client_key: "((etcd_client.private_key))"
        server_cert: "((etcd_server.certificate))"
        server_key: "((etcd_server.private_key))"
        peer_ca_cert: "((etcd_peer.ca))"
        peer_cert: "((etcd_peer.certificate))"
        peer_key: "((etcd_peer.private_key))"
  - name: etcd_metrics_server
    release: etcd
    properties:
      etcd_metrics_server:
        etcd:
          dns_suffix: etcd.service.cf.internal
          require_ssl: true
          ca_cert: "((etcd_client.ca))"
          client_cert: "((etcd_client.certificate))"
          client_key: "((etcd_client.private_key))"
  - name: metron_agent
    release: loggregator
    properties: *metron_agent_properties
  update:
    serial: true
    max_in_flight: 1

- name: doppler
  azs:
  - z1
  instances: 1
  persistent_disk_type: 1GB
  vm_type: common
  stemcell: default
  networks:
  - name: loggregator
  jobs:
  - name: consul_agent
    release: consul
    properties:
      consul:
        agent:
          mode: client
          domain: cf.internal
          servers: *consul_servers
          services:
            doppler:
              name: doppler
        require_ssl: true
        encrypt_keys: "((consul_encrypt_keys))"
        agent_cert: "((consul_agent.certificate))"
        agent_key: "((consul_agent.private_key))"
        ca_cert: "((consul_agent.ca))"
        server_cert: "((consul_server.certificate))"
        server_key: "((consul_server.private_key))"
  - name: doppler
    release: loggregator
    properties:
      doppler:
        etcd:
          client_cert: "((etcd_client.certificate))"
          client_key: "((etcd_client.private_key))"
        syslog_skip_cert_verify: true
      loggregator:
        tls:
          ca_cert: "((loggregator_tls_ca_cert))"
          doppler:
            cert: "((loggregator_tls_doppler_cert))"
            key: "((loggregator_doppler.private_key))"
        etcd:
          require_ssl: true
          ca_cert: "((etcd_client.ca))"
          machines: [etcd.service.cf.internal]
      doppler_endpoint:
        shared_secret: "((dropsonde_shared_secret))"
  - name: metron_agent
    release: loggregator
    properties: *metron_agent_properties

- name: log-api
  azs:
  - z1
  instances: 1
  persistent_disk_type: 1GB
  vm_type: common
  stemcell: default
  networks:
  - name: loggregator
  jobs:
  - name: consul_agent
    release: consul
    properties:
      consul:
        agent:
          mode: client
          domain: cf.internal
          servers: *consul_servers
          services:
            loggregator_trafficcontroller: {}
        require_ssl: true
        encrypt_keys: "((consul_encrypt_keys))"
        agent_cert: "((consul_agent.certificate))"
        agent_key: "((consul_agent.private_key))"
        ca_cert: "((consul_agent.ca))"
        server_cert: "((consul_server.certificate))"
        server_key: "((consul_server.private_key))"
  - name: loggregator_trafficcontroller
    release: loggregator
    properties:
      cc:
        srv_api_uri: ""
      uaa:
        url: ""
      system_domain: unused
      traffic_controller:
        disable_access_control: true
        etcd:
          client_cert: "((etcd_client.certificate))"
          client_key: "((etcd_client.private_key))"
      loggregator:
        tls:
          ca_cert: "((loggregator_tc.ca))"
          trafficcontroller:
            cert: "((loggregator_tc.certificate))"
            key: "((loggregator_tc.private_key))"
        etcd:
          require_ssl: true
          ca_cert: "((etcd_client.ca))"
          machines: [etcd.service.cf.internal]
      ssl:
        skip_cert_verify: false
  - name: metron_agent
    release: loggregator
    properties: *metron_agent_properties
  update:
    max_in_flight: 1
    serial: true

variables:
- name: loggregator_ca
  type: certificate
  options:
    common_name: loggregatorCA
- name: loggregator_doppler
  type: certificate
  options:
    ca: loggregator_ca
    common_name: doppler
    ext_key_usage:
    - server_auth
- name: loggregator_tc
  type: certificate
  options:
    ca: loggregator_ca
    common_name: trafficcontroller
    ext_key_usage:
    - client_auth
- name: etcd_ca
  type: certificate
  options:
    common_name: etcdCA
- name: etcd_server
  type: certificate
  options:
    ca: etcd_ca
    common_name: etcd.service.cf.internal
    alternative_names:
    - "*.etcd.service.cf.internal"
    - etcd.service.cf.internal
    ext_key_usage:
    - server_auth
- name: etcd_client
  type: certificate
  options:
    ca: etcd_ca
    common_name: clientName
    ext_key_usage:
    - client_auth
- name: etcd_peer_ca
  type: certificate
  options:
    common_name: peerCA
- name: etcd_peer
  type: certificate
  options:
    ca: etcd_peer_ca
    common_name: etcd.service.cf.internal
    alternative_names:
    - "*.etcd.service.cf.internal"
    - etcd.service.cf.internal
    ext_key_usage:
    - client_auth
    - server_auth
- name: consul_agent_ca
  type: certificate
  options:
    common_name: consulCA
- name: consul_agent
  type: certificate
  options:
    ca: consul_agent_ca
    common_name: consul_agent
    ext_key_usage:
    - client_auth
    - server_auth
- name: consul_server
  type: certificate
  options:
    ca: consul_agent_ca
    common_name: server.dc1.cf.internal
    ext_key_usage:
    - client_auth
    - server_auth

update:
  canaries: 10
  max_in_flight: 10
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: true
